import { createRouter } from '../middleware/async'
import clientsRouter = require('./admin-clients.routes')
import billingRouter = require('./admin-billing.routes')
import providersRouter = require('./admin-providers.routes')
import settingsRouter = require('./admin-settings.routes')
import tunnelRouter = require('./admin-tunnel.routes')
import simulatorRouter = require('./admin-simulator.routes')
import usageRouter = require('./admin-usage.routes')
import pricingRouter = require('./admin-pricing.routes')
import cartaRouter = require('./admin-carta.routes')
import pagosRouter = require('./admin-pagos.routes')
import motorizadosRouter = require('./admin-motorizados.routes')
import ciudadesRouter = require('./admin-ciudades.routes')
import cooperativasRouter = require('./admin-cooperativas.routes')
import incidenciasRouter = require('./admin-incidencias.routes')

const router = createRouter()

router.use(clientsRouter)
router.use(billingRouter)
router.use(providersRouter)
router.use(settingsRouter)
router.use(tunnelRouter)
router.use(simulatorRouter)
router.use(usageRouter)
router.use(pricingRouter)
router.use(cartaRouter)
router.use(pagosRouter)
router.use(motorizadosRouter)
router.use(ciudadesRouter)
router.use(cooperativasRouter)
router.use(incidenciasRouter)

export = router
